"""Template generation for release-checklist init command."""


GENERAL_TEMPLATE = """\
# Release Readiness Gate Configuration — General
# Generated by release-checklist init
# Run: release-checklist validate this-file.yaml

metadata:
  project: "YOUR_PROJECT_NAME"
  version: "1.0.0"
  environment: "production"
  regulated_industry: "general"
  risk_classification: "high"
  deployment_date: null
  deployment_owner: null

model_validation:
  performance:
    accuracy_threshold: 0.90
    bias_evaluation_complete: false
    adversarial_testing_complete: false
  fairness:
    disparate_impact_ratio: 0.80
    subgroup_performance_review: false

governance:
  documentation:
    model_card_complete: false
    risk_assessment_complete: false
    explainability_report_complete: false
  approvals:
    technical_review: false
    ai_governance_review: false
    legal_review: false
    security_review: false
  regulatory: {}

infrastructure:
  testing:
    unit_tests_passing: false
    integration_tests_passing: false
    security_scan_passed: false
    load_test_passed: false
  monitoring:
    alerting_configured: false
    drift_detection_enabled: false
  rollback:
    rollback_plan_documented: false
    rollback_tested: false

incident_readiness:
  runbook_complete: false
  escalation_contacts_defined: false
"""

HEALTHCARE_TEMPLATE = """\
# Release Readiness Gate Configuration — Healthcare
# Generated by release-checklist init --industry healthcare
# Includes HIPAA and clinical AI specific gates

metadata:
  project: "YOUR_PROJECT_NAME"
  version: "1.0.0"
  environment: "production"
  regulated_industry: "healthcare"
  risk_classification: "high"
  deployment_date: null
  deployment_owner: null
  regulatory_contact: null
  hipaa_covered_entity: true

model_validation:
  performance:
    accuracy_threshold: 0.95
    sensitivity_threshold: 0.90
    specificity_threshold: 0.90
    bias_evaluation_complete: false
    subgroup_performance_review: false
    adversarial_testing_complete: false
  clinical_validation:
    clinical_expert_review_complete: false
    prospective_validation_complete: false
    failure_mode_analysis_complete: false

governance:
  documentation:
    model_card_complete: false
    risk_assessment_complete: false
    intended_use_statement: false
    contraindications_documented: false
    explainability_report_complete: false
  approvals:
    technical_review: false
    ai_governance_review: false
    legal_review: false
    security_review: false
    clinical_leadership_approval: false
  regulatory:
    hipaa_assessment_complete: false
    phi_handling_reviewed: false
    fda_510k_applicable: false

infrastructure:
  testing:
    unit_tests_passing: false
    integration_tests_passing: false
    security_scan_passed: false
    load_test_passed: false
    phi_data_not_in_logs: false
  monitoring:
    alerting_configured: false
    drift_detection_enabled: false
    phi_access_audit_logging: false
  rollback:
    rollback_plan_documented: false
    rollback_tested: false
    patient_impact_rollback_plan: false

incident_readiness:
  runbook_complete: false
  escalation_contacts_defined: false
  clinical_incident_escalation: false
  patient_safety_protocol: false
"""

FINANCE_TEMPLATE = """\
# Release Readiness Gate Configuration — Financial Services
# Generated by release-checklist init --industry finance
# Includes SR 11-7 model risk management gates

metadata:
  project: "YOUR_PROJECT_NAME"
  version: "1.0.0"
  environment: "production"
  regulated_industry: "finance"
  risk_classification: "high"
  deployment_date: null
  deployment_owner: null
  model_risk_tier: "tier_1"  # tier_1 (highest) | tier_2 | tier_3

model_validation:
  performance:
    accuracy_threshold: 0.90
    bias_evaluation_complete: false
    disparate_impact_ratio: 0.80
    ecoa_adverse_action_tested: false
    adversarial_testing_complete: false
  model_risk:
    independent_validation_complete: false
    backtesting_complete: false
    stress_testing_complete: false
    challenger_model_comparison: false

governance:
  documentation:
    model_card_complete: false
    risk_assessment_complete: false
    model_inventory_entry_added: false
    explainability_report_complete: false
    adverse_action_codes_documented: false
  approvals:
    technical_review: false
    ai_governance_review: false
    legal_review: false
    model_risk_management_approval: false
    compliance_review: false
  regulatory:
    sr_11_7_compliance: false
    ecoa_fair_lending_review: false
    fcra_review: false

infrastructure:
  testing:
    unit_tests_passing: false
    integration_tests_passing: false
    security_scan_passed: false
    load_test_passed: false
  monitoring:
    alerting_configured: false
    drift_detection_enabled: false
    regulatory_reporting_configured: false
  rollback:
    rollback_plan_documented: false
    rollback_tested: false

incident_readiness:
  runbook_complete: false
  escalation_contacts_defined: false
  regulatory_incident_notification_plan: false
"""


TEMPLATES = {
    "general": GENERAL_TEMPLATE,
    "healthcare": HEALTHCARE_TEMPLATE,
    "finance": FINANCE_TEMPLATE,
    "insurance": FINANCE_TEMPLATE.replace("finance", "insurance").replace("Financial Services", "Insurance").replace("SR 11-7", "state insurance regulation"),
    "government": GENERAL_TEMPLATE,
}


def get_template(industry: str) -> str:
    """Return a release checklist template for the given industry."""
    return TEMPLATES.get(industry, TEMPLATES["general"])
